### PR TITLE
Add `(unreleased)` note

### PR DESCRIPTION
**Pull request by igoynawamreh**

### CODE REVIEW

**Comment by taufik-nurrohman** [comment]
Pakai editor apa kamu mas? Line-ending dibuang dulu ya!

https://github.com/mecha-cms/mecha/wiki/Editor-Settings

**Comment by igoynawamreh** [comment]
@taufik-nurrohman gak pakai editor mas langsung di editor github :v

**Comment by taufik-nurrohman** [comment]
Tekan `.` aja mas terus buat settingan kaya di Wiki. Ntar tak merge.

**Comment by igoynawamreh** [comment]
Aku rasa cuma ada EOL aja mas

**Pull request merged**
